//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_wydania_zewn
    {
        public int ID_wydania { get; set; }
        public Nullable<int> ID_pracownicy { get; set; }
        public Nullable<int> ID_zamowienia { get; set; }
        public Nullable<double> Ilosc_wydana { get; set; }
        public string Data_wydania { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
